### ISSUE TITLE
Support Django 4.x

### ISSUE THREAD

**Issue by tulgaab** [DjangoAdminHackers/django-admin-row-actions#26]
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django_admin_row_actions/__init__.py", line 1, in <module>
    from .admin import AdminRowActionsMixin
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django_admin_row_actions/admin.py", line 3, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls'`

**Comment by amaddio** [comment]
Related to this issue. I am updating from Django 3.2 to 4.2 (through 4.1). The error above is raised. Is there a newer version of `django-admin-row-actions` that fixes the problem?

If not, would you mind pulling my changes if I create a fork?

**Comment by jamesrampton** [comment]
Hi @amaddio you can find Django 4 compatibility in the `feature/django4` branch here: https://github.com/DjangoAdminHackers/django-admin-row-actions/tree/feature/django4

Thanks for submitting your PR; those changes are already in that branch though.

**Comment by amaddio** [comment]
Ah, thanks @jamesrampton. Great that there has been progress on this. Unfortunately, there is no release of this branch on [PyPI](https://pypi.org/search/?q=django-admin-row-actions). How can one install that package from a package manager (e.g. Poetry)?

**Comment by amaddio** [comment]
Never mind. I figured it out. In Poetry one could use: `poetry add "git+https://github.com/DjangoAdminHackers/django-admin-row-actions.git@feature/django4" -vvv`.

Are you planning on releasing, tagging or merging the other branch so that one would be able to retrieve future changes?

**Comment by blag** [comment]
@amaddio Working on that in PR #28. Do you mind giving that a quick review?

Looking forward to having this available on PyPI. 😄

**Comment by amaddio** [comment]
@blag sure. Feel free to add me as a reviewer. I am not a repo contributor yet but I don't mind to be ;-)

**Comment by blag** [comment]
I cannot add you as a reviewer, I think it's because you aren't a collaborator on this repository and you are not involved with that PR yet.
![Screen Shot 2023-09-25 at 3 59 11 PM](https://github.com/DjangoAdminHackers/django-admin-row-actions/assets/597113/69590faf-be3c-4bd8-bbc6-8360ecf51b71)

So if those changes look good to you, please drop a :+1: in the comments or something.

**Comment by amaddio** [comment]
@blag here is my review: https://github.com/DjangoAdminHackers/django-admin-row-actions/pull/28#pullrequestreview-1643997640

**Comment by blag** [comment]
Version 0.1.0 is now available on [PyPI](https://pypi.org/project/django-admin-row-actions/0.10.0/) and [GitHub](https://github.com/DjangoAdminHackers/django-admin-row-actions/releases/tag/v0.10.0) and contains support for Django 4.
